### ISSUE TITLE
read_string can't take an argument to override default encoding

### ISSUE THREAD

**Issue by karenetheridge** [rjbs/Mixin-Linewise#6]
...as described in https://github.com/rjbs/Dist-Zilla/issues/303

**Comment by rjbs** [comment]
Implemented in 0.107, but with the arguments in the opposite order, to match the `file` methods.

**Comment by karenetheridge** [comment]
Looks like this caused some problems for you. sorry about that.

**Comment by rjbs** [comment]
No worries, it was my own darn fault.
